### ISSUE TITLE
cannot directly open it via the pop up notification if the file name conatins " " (space)

### ISSUE THREAD

**Issue by vanceyen** [mozilla-tw/Rocket#1217] opened 2017-11-05 10:06 UTC
STR:
1.  Download a MP3 file from http://www.planetlagu.site/
2. When download complete, a notification will popup in the bottom of the screen
3. Select “Open” in the notification. 

Expected result:
Something will happen to allow user listen to the MP3 she just downloads

Actual result:
Nothing happen. But works fine if user tries to play the download MP3 from download list

DUT: Any device can reproduce this issue
Build: 1.0 - 1692

**Comment by chianger** [comment] 2017-11-06 02:37
user has workaround to go to 'download' panel and able to play. 
need to look into this as it seems to be a regression.

**Comment by chianger** [comment] 2017-11-28 03:58
close as #1225 is merged.

**Closed by chianger** 2017-11-28 03:58 UTC
Labels: Bug
