### ISSUE TITLE
(Google Play reviews) Moving to SD card not working

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2080] opened 2018-06-26 05:33 UTC
The application is good. But regarding the download feature on the SD card, no
running properly. Please fix it
Device Galaxy J5 (j5lte) App version 4869 (2.2.0(4869)) OS Android 6.0 

For me It's okay, maybe It's good but on my phone does not match,
so when the download process is complete I try to move the file download to sd card fixed
can not, please repair me .. !!!
Device Xperia™ M4 Aqua (E2303) App version — OS Android 6.0

**Comment by mTwTm** [comment] 2018-06-26 05:34
It's working on my Android 8 device. I'm also uncertain if these users are simply referring to that we should save directly to SDcard rather than move from local to SDcard after a file is downloaded.

**Comment by chianger** [comment] 2018-07-02 02:59
not sure if this is actionable but let's get it into triage meeting to decide.

**Comment by chianger** [comment] 2018-08-21 02:35
Need to figure out reproduce steps otherwise it's stilll not actionable.

**Comment by chianger** [comment] 2018-09-20 03:36
possible followup actions:
1. leverage cloud test lab to run script testing; or get target device to manually try reproducing
2.  monitor the google play comment reports (relman)

**Comment by chianger** [comment] 2018-10-19 06:53
QAWanted to check again if any possible path to reproduce this.

**Comment by chianger** [comment] 2018-10-23 07:52
If there's no path to reproduce let's close it as WORKSFORME.

**Comment by ivantw08** [comment] 2018-10-23 09:41
tried HTC android6.0 Cannot reproduce it .

**Closed by ivantw08** 2018-10-23 09:41 UTC
Labels: QAwanted
