### ISSUE TITLE
Visit an unavailable website and screenshot it will cause hang issue

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#872] opened 2017-09-20 08:18 UTC
STR:

1. visit http://wesley.huang
2. Tap Menu
3. Tap Screenshot

Expected Result:

3. Screenshot is taken

Actual Result:

3. Screen is hang

**Comment by Conjuror** [comment] 2017-09-20 08:26
btw, while connecting to wesley.huang, sometimes it's a blank page. Somtimes, it's a error page.

**Comment by chianger** [comment] 2017-09-21 02:56
Hard to reproduce at this moment.
Leave to decision pending but let's keep tracking this.

**Comment by chianger** [comment] 2017-09-26 09:47
Downgrade to P2 since this is more like edge case.
We would like to revisit it soon after Oct9.

**Comment by chianger** [comment] 2017-11-14 08:37
If we cannot reproduce it anymore, we can close it.
Keep P3 for tracking and leave QAWanted to try more times.

**Comment by cynthiatang** [comment] 2018-03-21 05:16
Verified: this issue cannot be reproduced. Thanks. :)

Device: Pixel 2
Rocket nightly: 1.0.4 (2910). nightly
Android version: 8.1.0
WebView version 65.0.3325.109

**Comment by NashTung** [comment] 2018-05-25 02:49
This issue cannot be reproduced
Video: https://drive.google.com/open?id=1zZGxkNdUgIxnlcj8Nro0asoPGJDzp8x2

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158

**Closed** 2018-06-05 09:56 UTC
Labels: Comp/ScreenCapture, S3
