### ISSUE TITLE
Enable web search to launch (incl. telemetry to track the usage of "web search")

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#432] opened 2017-08-28 07:33 UTC
STR:

1. launch zerda and visit a website
2. select a paragraph/text
3. tap "..." on the popup menu
4. select web search

Expected Result:

4. Search via current browser

Actual Result:

4. Suggest to search by other browser

**Comment by Conjuror** [comment] 2017-08-28 07:34
For an example, Fennec attempt to launch Google Search by default and keep the browsing experience within Fennec.

**Comment by idiotmax** [comment] 2017-08-28 19:18
We do have an entry called "SEARCH PRIVATELY", which already have a dup bug #429.
The entry "Web Search" is implemented by Chrome or other apps, we cannot remove it and should also honor user's choice. 

I suggest we close this one and follow up UX decision on #429.

**Comment by Conjuror** [comment] 2017-08-31 08:05
invalid issues

**Comment by mTwTm** [comment] 2018-01-10 08:31
This is actually possible, I saw this behavior with cliqz.

**Comment by chianger** [comment] 2018-01-15 07:49
S2: 2nd level menu function

**Comment by NashTung** [comment] 2018-05-17 06:36
This issue can be reproduced and the root cause as mxlius mentioned it.
Video:
https://drive.google.com/open?id=19Ok_MBKa1s5A7yGVEHeXQ784C7KZexUL

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment] 2018-08-14 07:34
I think this may be a great way to retain more users.

**Comment by joechengla** [comment] 2018-08-17 07:17
telemetry: 
we want to track the usage of "web search" by understanding how many users launch Rocket through the "web search" method, as part of the telemetry for other launch methods (add to homescreen, open link from 3rd party, app launch from launcher)

**Comment by mxlius** [comment] 2018-10-08 08:16
Closed by #2718

**Closed by mxlius** 2018-10-08 08:16 UTC
Labels: Comp/General, Feature-Backlog, size: M, telemetry-wanted
