### ISSUE TITLE
When setting save file to SD card, two completion reminders will appear after download file

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-tw/Rocket#1402] opened 2018-02-08 08:49 UTC
Device: Samsung S7 (SM-G930FD)
Android version: 7.0

As my phone can be installed SD card, rocket default file save location is SD card. After completing the file download or save the picture operation, two completion reminders will appear in drop-down menu.
![default](https://user-images.githubusercontent.com/17559985/35963057-79a5d648-0cee-11e8-8e9c-cf952bdcab78.png)

There will be only one reminder during the download, but it comes two after download finished.

If you set the save file to internal storage then there is no such problem.

I tested the browser that comes with the Samsung phone that also transfers the phone download manager. After setting save file to the SD card, there is only one completion reminder appear after downloading.

**Comment by mTwTm** [comment] 2018-02-09 05:14
I thought this was fixed in #1055 Sounds like S1 to me.

**Comment by chianger** [comment] 2018-02-12 08:04
Regression so I'm assuming P1 and put it in next sprint.

**Comment by mTwTm** [comment] 2018-03-06 10:00
Per testing on S7 7.0 and emulator 7.0 / 7.1.1 , it's an Android bug of an API we're using (DownloadManager.remove()) and is fixed since 7.1.1 There is no easy way to work around this.

**Comment by chianger** [comment] 2018-03-13 06:21
If other apps using system download manager should see this, sounds fine to postpone it

**Comment by weslyhuang** [comment] 2018-04-03 08:04
closed per discussion.

**Closed by weslyhuang** 2018-04-03 08:04 UTC
Labels: P1, S1
