### ISSUE TITLE
"Back" action is not completely right

### ISSUE THREAD

**Issue by rxumoz** [mozilla-tw/Rocket#1400] opened 2018-02-08 08:11 UTC
Actions: 
Start Rocket, browse website A, press "home" button to go to home, and then browse website B. Press "back" button,  it would turn to website A but not homepage.

Expectation:
Press "back" button and turn to homepage.

**Comment by mTwTm** [comment] 2018-02-08 08:23
This is the expected behavior per Rocket 1.0 (Since it's single tab) and we plan to change to the expected behavior you mentioned in our multitab feature @Jacklin-ux can you confirm?

**Comment by chianger** [comment] 2018-02-08 09:27
Let's close this bug for now. I believe the coming multi-tab feature will improve the user experience.
@rxumoz please don't hesitate to further post issues and feature suggestion.

**Closed by chianger** 2018-02-08 09:27 UTC
